#!/bin/bash
#
### BEGIN INIT INFO
# Provides: milter-smptauth
# Required-Start: $local_fs $network $syslog
# Required-Stop: $local_fs $network $syslog
# Short-Description: SMTPAuth filter.
# Description: Stop sending mail from spammer.
#              
### END INIT INFO

# smtpauth-manager: manager process of filter and logger processes.
#
# chkconfig: - 29 81
# description: Stop sending mail from spammer.
# processname: smtpauth-manager
# config: /etc/smtpauth/reject_ids.txt

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

RETVAL=0
PROG="smtpauth-manager"
PREFIX=/usr/local

THRESHOLD=20
PERIOD=60

CONFIG=/etc/sysconfig/smtpauth/filter
[ -f $CONFIG ] && . $CONFIG
CONFIG=/etc/sysconfig/smtpauth/log-collector
[ -f $CONFIG ] && . $CONFIG

start() {
        # Start daemons.

	# Check that networking is up.
	[ ${NETWORKING} = "no" ] && exit 1

	[ -x $PREFIX/bin/smtpauth-manager ] || exit 1

        echo -n $"Starting $PROG for $site: "
        mkdir -p /var/run/smtpauth /var/log/smtpauth /var/lib/smtpauth /var/lib/smtpauth/rrd
        chown smtpauth-manager:smtpauth-manager /var/run/smtpauth /var/log/smtpauth /var/lib/smtpauth/rrd

	options="--period $PERIOD --threshold $THRESHOLD --max_messages=$MAX_MESSAGES "
        case $AUTO_REJECT in
            [Yy][Ee][Ss])
		options="$options --auto_reject"
		;;
        esac

	case $GEOIP in
	    [Yy][Ee][Ss])
		options="$options --geoip_v4=$GEOIP_DATABASE_V4 --geoip_v6=$GEOIP_DATABASE_V6"
		;;
	esac

	case $ALERT_EMAIL in
	    [Yy][Ee][Ss])
		options="$options --alert_email"
		options="$options --alert_mailhost=$ALERT_MAILHOST --alert_port=$ALERT_PORT"
		options="$options --alert_sender=$ALERT_SENDER --alert_recipient=$ALERT_RECIPIENT"
		;;
	esac

        daemon $PREFIX/bin/smtpauth-manager $options
        RETVAL=$?
        echo
        if [ $RETVAL -eq 0 ] && [ ! -f /var/lock/subsys/$PROG ]; then
            touch /var/lock/subsys/$PROG
        else
            RETVAL=1
        fi
        return $RETVAL
}

stop() {
        # Stop daemons.
        echo -n $"Shutting down $PROG: "
        killproc $PROG
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$PROG
        return $RETVAL
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        RETVAL=$?
        ;;
  condrestart|try-restart|force-reload)
        if [ -f /var/lock/subsys/$PROG ]; then
            stop
            start
            RETVAL=$?
        fi
        ;;
  status)
        status $PROG
        RETVAL=$?
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
        exit 1
esac

exit $RETVAL
