#!/bin/bash
#
### BEGIN INIT INFO
# Provides: milter-smptauth
# Required-Start: $local_fs $network $syslog
# Required-Stop: $local_fs $network $syslog
# Short-Description: SMTPAuth filter.
# Description: Stop sending mail from spammer.
#              
### END INIT INFO

# smtpauth-manager: manager process of filter and logger processes.
#
# chkconfig: - 60 50
# description: Stop sending mail from spammer.
# processname: smtpauth-manager
# config: /etc/smtp_auth_filter/reject_ids.txt

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

RETVAL=0
prog="smtpauth-manager"

start() {
        # Start daemons.

	# Check that networking is up.
	[ ${NETWORKING} = "no" ] && exit 1

	[ -x /usr/local/bin/smtpauth-manager ] || exit 1

        echo -n $"Starting $prog for $site: "
        daemon /usr/local/bin/smtpauth-manager
        RETVAL=$?
        echo
        if [ $RETVAL -eq 0 ] && [ ! -f /var/lock/subsys/$prog ]; then
            touch /var/lock/subsys/$prog
        else
            RETVAL=1
        end
        return $RETVAL
}

stop() {
        # Stop daemons.
        echo -n $"Shutting down $prog: "
        killproc $prog
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
        return $RETVAL
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        RETVAL=$?
        ;;
  condrestart|try-restart|force-reload)
        if [ -f /var/lock/subsys/$prog ]; then
            stop
            start
            RETVAL=$?
        fi
        ;;
  status)
        status $prog
        RETVAL=$?
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
        exit 1
esac

exit $RETVAL
