#!/bin/bash
#
### BEGIN INIT INFO
# Provides: milter-smptauth-log-collector
# Required-Start: $local_fs $network $syslog
# Required-Stop: $local_fs $network $syslog
# Short-Description: SMTPAuth log-collector.
# Description: Stop sending mail from spammer.
#              
### END INIT INFO

# smtpauth-log-collector: smtpauth-log-collector processes.
#
# chkconfig: - 29 81
# description: Stop sending mail from spammer.
# processname: smtpauth-log-collector
# config: /etc/smtpauth/reject_ids.txt

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

THRESHOLD=20
PERIOD=60

CONFIG=/etc/sysconfig/smtpauth/log-collector
[ -f $CONFIG ] && . $CONFIG

RETVAL=0
PROG="smtpauth-log-collector"
PREFIX=/usr/local

RECV_ADDRESS=${LOGGER_ADDRESS:-unix:/var/run/smtpauth/log-collector.sock}
LOG_FILE=${LOG_FILE:-/var/log/smtpauth/stats.log}
PID_FILE=${PID_FILE:-/var/run/smtpauth/log-collector.pid}

start() {
        # Start daemons.

	# Check that networking is up.
	[ ${NETWORKING} = "no" ] && exit 1

	[ -x ${PREFIX}/bin/smtpauth-log-collector ] || exit 1

        echo -n $"Starting $PROG for $site: "
        mkdir -p /var/run/smtpauth /var/log/smtpauth
        chown smtpauth-manager:smtpauth-manager /var/run/smtpauth /var/log/smtpauth

	options="--recv_address=$RECV_ADDRESS --log=$LOG_FILE --period=$PERIOD --threshold=$THRESHOLD --pid_file=$PID_FILE"
        case $AUTO_REJECT in
        [Yy][Ee][Ss])
            options="$options --auto_reject"
            ;;
        esac

        daemon ${PREFIX}/bin/${PROG} $options
        RETVAL=$?
        echo
        if [ $RETVAL -eq 0 ] && [ ! -f /var/lock/subsys/$PROG ]; then
            touch /var/lock/subsys/$PROG
        else
            RETVAL=1
        fi
        return $RETVAL
}

stop() {
        # Stop daemons.
        echo -n $"Shutting down $PROG: "
        killproc $PROG
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$PROG
        return $RETVAL
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        RETVAL=$?
        ;;
  condrestart|try-restart|force-reload)
        if [ -f /var/lock/subsys/$PROG ]; then
            stop
            start
            RETVAL=$?
        fi
        ;;
  status)
        status $PROG
        RETVAL=$?
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
        exit 1
esac

exit $RETVAL
